### PR TITLE
Fix multiilayer slicing

### PR DESCRIPTION
**Pull request by github-4o**

### CODE REVIEW

**Comment by github-4o** [comment]
statistics got broked in action. they show 0 domains detected

**Comment by github-4o** [comment]
nop, it was dead from the beginning

**Comment by github-4o** [comment]
nop, it was alive

**Review by ffffffcat — APPROVED** [review]

**Comment by github-4o** [comment]
nein nein nein nein nein ... nein
it was a draft cause the branch introduced a bug

**Comment by github-4o** [comment]
continued in #71

**Pull request merged**
